### PR TITLE
Cutscene

### PR DESCRIPTION
**Pull request by ExtraGravity**

### CODE REVIEW

**Comment by CalebJohn** [comment]
enochtsang There are to many commits in this pull, you should use [git rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i/) to remove the less meaningful commits and the ones that contain code that aren't present in the final pull. Let me know if you need any help.

**Comment by ExtraGravity** [comment]
I like the granularity ;o I'll fix it up though

**Comment by clayjohn** [comment]
Looks good to me, merge it whenever you are happy Caleb.

**Comment by ExtraGravity** [comment]
Bungled the rebase super hard closing

**Pull request closed without merging**
