### PR TITLE
Skeleton For Cutscenes

### PR DESCRIPTION
**Pull request by ExtraGravity**
static background, added sprite animation for moving cutscene, added world generator skeleton code, added comments for how to build on the code

CI is failing because this branch does not have a `travis.yml`.

### CODE REVIEW

**Comment by clayjohn** [comment]
So this is failing the travis check, do we merge it or no?

**Comment by CalebJohn** [comment]
It won't pass travis unless @enochtsang  merges master into this branch, which I don't recommend (it's unnecessary). We should just review this ourselves.

**Comment by ExtraGravity** [comment]
Why do you not suggest it? I think it's easy enough to do.

**Comment by clayjohn** [comment]
Oh, in that case it looks good to me.

**Comment by CalebJohn** [comment]
@enochtsang it is but this pull is small enough that I just don't see a point in it.

**Comment by CalebJohn** [comment]
@enochtsang This is really solid, except for the loadingImage which seems to be missing. This will be ready for merge once we get that in!

edit: btw you shouldn't worry about squashing this commit.

We should also talk about how we have game assigned, should we keep it defined under window?

**Comment by clayjohn** [comment]
Can we merge this now?

**Comment by CalebJohn** [comment]
Looks good! Merging.

**Pull request merged**
